# Generated by Django 5.0.3 on 2024-04-01 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MealDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='recipe_images'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_holiday',
            field=models.ManyToManyField(help_text='Hold ctrl or cmd to select more than one option', to='recipe.holidaymeal'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_diet',
            field=models.ManyToManyField(help_text='Hold ctrl or cmd to select more than one option', to='recipe.mealdiet'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.mealtype'),
        ),
    ]
